### ISSUE TITLE
udev rule does not trigger

### ISSUE THREAD

**Issue by stapelberg** [Yubico/libu2f-host#28] opened 2015-09-16 08:13 UTC
On a freshly-installed Debian jessie (tested both with systemd/udev 215 from jessie and systemd/udev 225 from testing), the udev rule shipped with libu2f-host does not trigger when I insert my Yubikey NEO:

```
KERNEL=="hidraw*", SUBSYSTEM=="hidraw", ATTRS{idVendor}=="1050", ATTRS{idProduct}=="0113|0114|0115|0116|0120|0402|0403|0406|0407|0410", TAG+="uaccess"
```

I believe this is because the hidraw kernel/subsystem is not set at the same level when the usb vendor/product id are set (see the udevadm info below).

Removing the kernel/subsystem attributes from the rule makes it work:

```
ATTRS{idVendor}=="1050", ATTRS{idProduct}=="0113|0114|0115|0116|0120|0402|0403|0406|0407|0410", TAG+="uaccess"
```

This is the udevadm test output of the device in question:

```
udevadm info -a /dev/usb/hiddev0

Udevadm info starts with the device specified by the devpath and then
walks up the chain of parent devices. It prints for every device
found, all possible attributes in the udev rules key format.
A rule to match, can be composed by the attributes of the device
and the attributes from one single parent device.

  looking at device '/devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1:1.0/usbmisc/hiddev0':
    KERNEL=="hiddev0"
    SUBSYSTEM=="usbmisc"
    DRIVER==""

  looking at parent device '/devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1:1.0':
    KERNELS=="1-1:1.0"
    SUBSYSTEMS=="usb"
    DRIVERS=="usbhid"
    ATTRS{bAlternateSetting}==" 0"
    ATTRS{bInterfaceClass}=="03"
    ATTRS{bInterfaceNumber}=="00"
    ATTRS{bInterfaceProtocol}=="00"
    ATTRS{bInterfaceSubClass}=="00"
    ATTRS{bNumEndpoints}=="02"
    ATTRS{supports_autosuspend}=="1"

  looking at parent device '/devices/pci0000:00/0000:00:14.0/usb1/1-1':
    KERNELS=="1-1"
    SUBSYSTEMS=="usb"
    DRIVERS=="usb"
    ATTRS{authorized}=="1"
    ATTRS{avoid_reset_quirk}=="0"
    ATTRS{bConfigurationValue}=="1"
    ATTRS{bDeviceClass}=="00"
    ATTRS{bDeviceProtocol}=="00"
    ATTRS{bDeviceSubClass}=="00"
    ATTRS{bMaxPacketSize0}=="64"
    ATTRS{bMaxPower}=="30mA"
    ATTRS{bNumConfigurations}=="1"
    ATTRS{bNumInterfaces}==" 1"
    ATTRS{bcdDevice}=="0333"
    ATTRS{bmAttributes}=="80"
    ATTRS{busnum}=="1"
    ATTRS{configuration}==""
    ATTRS{devnum}=="7"
    ATTRS{devpath}=="1"
    ATTRS{idProduct}=="0113"
    ATTRS{idVendor}=="1050"
    ATTRS{ltm_capable}=="no"
    ATTRS{manufacturer}=="Yubico"
    ATTRS{maxchild}=="0"
    ATTRS{product}=="Yubikey NEO U2F"
    ATTRS{quirks}=="0x0"
    ATTRS{removable}=="unknown"
    ATTRS{speed}=="12"
    ATTRS{urbnum}=="14"
    ATTRS{version}==" 2.00"

  looking at parent device '/devices/pci0000:00/0000:00:14.0/usb1':
    KERNELS=="usb1"
    SUBSYSTEMS=="usb"
    DRIVERS=="usb"
    ATTRS{authorized}=="1"
    ATTRS{authorized_default}=="1"
    ATTRS{avoid_reset_quirk}=="0"
    ATTRS{bConfigurationValue}=="1"
    ATTRS{bDeviceClass}=="09"
    ATTRS{bDeviceProtocol}=="01"
    ATTRS{bDeviceSubClass}=="00"
    ATTRS{bMaxPacketSize0}=="64"
    ATTRS{bMaxPower}=="0mA"
    ATTRS{bNumConfigurations}=="1"
    ATTRS{bNumInterfaces}==" 1"
    ATTRS{bcdDevice}=="0401"
    ATTRS{bmAttributes}=="e0"
    ATTRS{busnum}=="1"
    ATTRS{configuration}==""
    ATTRS{devnum}=="1"
    ATTRS{devpath}=="0"
    ATTRS{idProduct}=="0002"
    ATTRS{idVendor}=="1d6b"
    ATTRS{ltm_capable}=="no"
    ATTRS{manufacturer}=="Linux 4.1.0-2-amd64 xhci-hcd"
    ATTRS{maxchild}=="11"
    ATTRS{product}=="xHCI Host Controller"
    ATTRS{quirks}=="0x0"
    ATTRS{removable}=="unknown"
    ATTRS{serial}=="0000:00:14.0"
    ATTRS{speed}=="480"
    ATTRS{urbnum}=="126"
    ATTRS{version}==" 2.00"

  looking at parent device '/devices/pci0000:00/0000:00:14.0':
    KERNELS=="0000:00:14.0"
    SUBSYSTEMS=="pci"
    DRIVERS=="xhci_hcd"
    ATTRS{broken_parity_status}=="0"
    ATTRS{class}=="0x0c0330"
    ATTRS{consistent_dma_mask_bits}=="64"
    ATTRS{d3cold_allowed}=="1"
    ATTRS{device}=="0x9cb1"
    ATTRS{dma_mask_bits}=="64"
    ATTRS{driver_override}=="(null)"
    ATTRS{enable}=="1"
    ATTRS{irq}=="42"
    ATTRS{local_cpulist}=="0-3"
    ATTRS{local_cpus}=="0f"
    ATTRS{msi_bus}=="1"
    ATTRS{numa_node}=="-1"
    ATTRS{subsystem_device}=="0x2227"
    ATTRS{subsystem_vendor}=="0x17aa"
    ATTRS{vendor}=="0x8086"

  looking at parent device '/devices/pci0000:00':
    KERNELS=="pci0000:00"
    SUBSYSTEMS==""
    DRIVERS==""
```

**Comment by luthfii** [comment] 2015-10-21 11:59
I'm using debian wheezy. Because udev version in wheezy is still 170, i use udev from backports which is > 188. I tried remove kernel/subsystem attributes but still doesn't work. I use yubikey special key. I added 70-u2f.rules to /etc/udev/rules.d/ , but still no luck. Anyone here have the solution?

**Comment by zv** [comment] 2015-10-24 04:18
systemd has restructured the way tagged devices work (you can read about it more [here](http://cgit.freedesktop.org/systemd/systemd/tree/NEWS))

You can supply a new rule like the following
```
# Yubico YubiKey
ATTRS{idVendor}=="1050", ATTR{manufacturer}=="Yubico", OWNER="zv"
```

**Comment by luthfii** [comment] 2015-11-07 01:36
Now, it's working after read this tutorial. https://lehwalder.wordpress.com/2014/11/08/nutzung-des-plug-up-fido-u2f-key-unter-linux-mit-chrome-v38/

**Comment by FlorianKuehne** [comment] 2015-11-14 18:34
A simple copy and paste of 
>ATTRS{idVendor}=="1050", ATTRS{idProduct}=="0113|0114|0115|0116|0120|0402|0403|0406|0407|0410", TAG+="uaccess"

into a new file  **/etc/udev/rules.d/10-security-key.rules**, as mentioned in https://lehwalder.wordpress.com/2014/11/08/nutzung-des-plug-up-fido-u2f-key-unter-linux-mit-chrome-v38/
worked fine for me on Jessie with systemd v221

**Comment by tim-seoss** [comment] 2015-11-30 11:38
stapelberg's fix works for me and looks correct, can we get it merged?

I think the only place it wouldn't work is if you had a composite USB device which presented some interfaces which you didn't want to give the logged in user access to.  Seems unlikely?

Thanks,

Tim.

**Comment by klali** [comment] 2015-12-03 08:53
The current 70-u2f.rules works fine in ubuntu 15.10 which has systemd/udev 225.
I'm happy to add a third file and check for one more udev version if that's needed, but it seems unclear from what version this change is in effect, or if they made the old rules work again.

**Comment by tim-seoss** [comment] 2015-12-03 13:12
I'm testing with the udev package version 215-17+deb8u2 from Debian Jessie amd64.  I can't now get the current one to fail on the amd64 machine which I was previously seeing the failure on, neither does it fail on a second machine which I've just checked.  So, not sure what's going on here - could be a race potentially or my error?   Dunno :-(

**Comment by elvarb** [comment] 2016-05-01 22:43
Ok, spent the last hour or so trying to login to Github with my key for other stuff but I found this while debugging.

The problem with the udev file is that it specifies hidraw but that is not always the case.

`KERNEL=="hidraw*", SUBSYSTEM=="hidraw", ATTRS{idVendor}=="1050", ATTRS{idProduct}=="0113|0114|0115|0116|0120|0402|0403|0406|0407|0410", TAG+="uaccess"`

The device though looks like this

```
looking at parent device '/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.6':
    KERNELS=="2-1.6"
    SUBSYSTEMS=="usb"
    DRIVERS=="usb"
```

So I modified the rule to this

`ATTRS{idVendor}=="1050", ATTRS{idProduct}=="0113|0114|0115|0116|0120|0402|0403|0406|0407|0410", TAG+="uaccess"`

This is on Ubuntu 16.04

**Comment by jdanekrh** [comment] 2017-08-05 11:22
My, possibly unrelated problems with matching symptoms (=device was inaccessible from my user account), was that `TAG+="uaccess"` has somehow stopped working for me. I have NixOS with udev version 233. I had to use the more traditional udev line

        KERNEL=="hidraw*", SUBSYSTEM=="hidraw", GROUP="users", MODE="0660"

**Comment by AlD** [comment] 2017-09-20 01:12
I saw that you were concerned about compatibility with Ubuntu in the past, so I tested this on the current LTS release. It turned out that it requires the same fix nowadays:

```
root@ubuntu:/etc/udev/rules.d# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

root@ubuntu:/etc/udev/rules.d# grep 1050 70-u2f.rules
KERNEL=="hidraw*", SUBSYSTEM=="hidraw", ATTRS{idVendor}=="1050", ATTRS{idProduct}=="0113|0114|0115|0116|0120|0200|0211|0402|0403|0406|0407|0410", TAG+="uaccess"

root@ubuntu:/etc/udev/rules.d# udevadm trigger

root@ubuntu:/etc/udev/rules.d# udevadm info /sys/bus/usb/devices/2-1/
P: /devices/pci0000:00/0000:00:05.0/usb2/2-1
N: bus/usb/002/002
E: BUSNUM=002
E: DEVNAME=/dev/bus/usb/002/002
E: DEVNUM=002
E: DEVPATH=/devices/pci0000:00/0000:00:05.0/usb2/2-1
E: DEVTYPE=usb_device
E: DRIVER=usb
E: ID_BUS=usb
E: ID_MODEL=Yubico_WinUSB_Gnubby__gnubby1_
E: ID_MODEL_ENC=Yubico\x20WinUSB\x20Gnubby\x20\x28gnubby1\x29
E: ID_MODEL_FROM_DATABASE=Gnubby
E: ID_MODEL_ID=0211
E: ID_REVISION=0034
E: ID_SERIAL=Yubico_Yubico_WinUSB_Gnubby__gnubby1_
E: ID_USB_INTERFACES=:ff0000:
E: ID_VENDOR=Yubico
E: ID_VENDOR_ENC=Yubico
E: ID_VENDOR_FROM_DATABASE=Yubico.com
E: ID_VENDOR_ID=1050
E: MAJOR=189
E: MINOR=129
E: PRODUCT=1050/211/34
E: SUBSYSTEM=usb
E: TYPE=0/0/0
E: USEC_INITIALIZED=2819800

root@ubuntu:/etc/udev/rules.d# sed -i -re 's/KERNEL=="hidraw\*", SUBSYSTEM=="hidraw", //' 70-u2f.rules 

root@ubuntu:/etc/udev/rules.d# grep 1050 70-u2f.rules
ATTRS{idVendor}=="1050", ATTRS{idProduct}=="0113|0114|0115|0116|0120|0200|0211|0402|0403|0406|0407|0410", TAG+="uaccess"

root@ubuntu:/etc/udev/rules.d# udevadm trigger

root@ubuntu:/etc/udev/rules.d# udevadm info /sys/bus/usb/devices/2-1/
P: /devices/pci0000:00/0000:00:05.0/usb2/2-1
N: bus/usb/002/002
E: BUSNUM=002
E: DEVNAME=/dev/bus/usb/002/002
E: DEVNUM=002
E: DEVPATH=/devices/pci0000:00/0000:00:05.0/usb2/2-1
E: DEVTYPE=usb_device
E: DRIVER=usb
E: ID_BUS=usb
E: ID_FOR_SEAT=usb-pci-0000_00_05_0-usb-0_1
E: ID_MODEL=Yubico_WinUSB_Gnubby__gnubby1_
E: ID_MODEL_ENC=Yubico\x20WinUSB\x20Gnubby\x20\x28gnubby1\x29
E: ID_MODEL_FROM_DATABASE=Gnubby
E: ID_MODEL_ID=0211
E: ID_PATH=pci-0000:00:05.0-usb-0:1
E: ID_PATH_TAG=pci-0000_00_05_0-usb-0_1
E: ID_REVISION=0034
E: ID_SERIAL=Yubico_Yubico_WinUSB_Gnubby__gnubby1_
E: ID_USB_INTERFACES=:ff0000:
E: ID_VENDOR=Yubico
E: ID_VENDOR_ENC=Yubico
E: ID_VENDOR_FROM_DATABASE=Yubico.com
E: ID_VENDOR_ID=1050
E: MAJOR=189
E: MINOR=129
E: PRODUCT=1050/211/34
E: SUBSYSTEM=usb
E: TAGS=:seat:uaccess:
E: TYPE=0/0/0
E: USEC_INITIALIZED=2819800
```
Since the match is only broadened, not narrowed, this shouldn't break any other setups anyway.

**Comment by AlD** [comment] 2017-09-20 01:26
@jdanekrh still works for me with TAG+="uaccess" on archlinux with udev 234.

**Comment by klali** [comment] 2017-09-20 07:28
The device with productid 0x211 isn't a u2f device, or more accurately it isn't a u2f hid device that can be used by this library. Do you get the same behaviour with a standard u2f device?

**Comment by AlD** [comment] 2017-09-20 07:36
You are right and I think that's also the root cause of this bug.
I think the appropriate fix would be to leave the file in this project unchanged, since it targets only devices that actually do U2 for over hid.

Instead the instructions at https://www.yubico.com/support/knowledge-base/categories/articles/can-set-linux-system-use-u2f should link to a different file that supports both types of devices.

**Comment by nevun** [comment] 2020-10-14 12:23
We are archiving this project and closing issues. Please open a new one in the replacement library's repo: https://github.com/Yubico/libfido2 if it is still applicable.

**Closed by nevun** 2020-10-14 12:23 UTC
